services:
  - type: web
    name: readycollaborate-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npx prisma db push && npx prisma generate
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
